name: open-source-license-check-backend

on:
  push:
    branches:    
      - main

jobs:
  open-source-license-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install pipenv pyenv
      # note that we use the system python for installing at the moment
      - run: cd ./backend && pipenv install --system
      - run: gem install license_finder
      - run: license_finder
