name: open-source-license-check-backend

on:
  push:
    branches:    
      - main

jobs:
  open-source-license-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd ./backend && pip install pipenv && pipenv install
      - run: gem install license_finder
      - run: license_finder
