name: open-source-license-check-backend

on:
  push:
    branches:    
      - main

jobs:
  open-source-license-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install pipenv
      # note that we use the system python for installing at the moment
      - run: cd ./backend && pipenv install --system
      # install as a user to avoid the following error:
      # You don't have write permissions for the /var/lib/gems/3.0.0 directory.
      - run: gem install license_finder --user-install
      - run: license_finder
